### ISSUE TITLE
tata question

### ISSUE THREAD

**Issue by karlo2105** [back-to/streamlink_plugins#3]
Just tested this plugin you made and works great. 
Sky Sport 1 and 2 propose dual audio, but it's not covered by HDS plugin so far. 

As you can see in this text below two audios are aired **qae** as default and **qaf** as alternative : 

`EXTM3U
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="aac",NAME="qae a1",DEFAULT=YES,AUTOSELECT=YES,LANGUAGE="qae"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="aac",NAME="qaf a2",DEFAULT=NO,AUTOSELECT=YES,LANGUAGE="qaf",URI="tracks-a2/index.m3u8?token=ba13e65b-14956649486367"
#EXT-X-STREAM-INF:AUDIO="aac",RESOLUTION=720x396,CODECS="avc1.4d001f,mp4a.40.2",BANDWIDTH=1693370
tracks-v1a1/index.m3u8?token=ba13e65b-14956649486367
`
You can also notice it on their player which is displayed by small microphone on bottom right on those two channels.

When I just change this address : 
`https://s4.skyfall.to/SkySport1/manifest.f4m?token=5cbfda0f-14956660976495` to this one below `https://s4.skyfall.to/SkySport1/index.m3u8?token=5cbfda0f-14956660976495`

I can manually choose alternative audio with this command : --hls-audio-select=qaf
I would like to ask you, could you please add HLS support to this plugin and set it by default priority as it would allow dual audio choice ?

Thanks very much for your contribution. :)

**Comment by back-to** [comment]
https://github.com/back-to/streamlink_plugins/commit/e32ab754f530add1936348d5cb38e9961a6ba43a

you still will need the `--hls-audio-select` command,
I could not found an option in streamlink, that would auto start a stream with multi audio.

maybe I missed it ...
if you know a plugin where you can choose the audio without `--hls-audio-select` let me know

**Comment by karlo2105** [comment]
Beardypig told me that auto multi muxing is not covered so far by streamlink. To add multi audio muxing, all audio should be muxed simultaneously by ffmpeg and I don't know whether or not it's possible. But this hls audio select switch is a good workaround so far even if it's manual.

**Comment by karlo2105** [comment]
@back-to @beardypig
Just to point out I get both audio tracks muxed simultaneously in VLC with command below and thus I can make choice in VLC directly. Qaf is audio ID of second audio track. 
```
streamlink --hls-audio-select=qaf "https://www.tata.to/channel/sky-sport-1" best
[cli][info] Found matching plugin tata for URL https://www.tata.to/channel/sky-sport-1
[cli][info] Available streams: 128k (worst), 995k, 1491k (best)
[cli][info] Opening stream: 1491k (hls-multi)
[cli][info] Starting player: "C:\Program Files\VideoLAN\VLC\vlc.exe"
[cli][info] Player closed
```

Amazing discover. ;)
